### ISSUE TITLE
No reply after pressing "check"

### ISSUE THREAD

**Issue by Pozdniakov** [agricolamz/checkdown#1]
This document is knitted but pressing "check" doe not return "Correct" or whatever else. Seems that the page is reloaded after pressing the button.

P.S. Example from [docs](https://github.com/agricolamz/checkdown/blob/master/docs/index.Rmd) works well.

I deleted all asterisks from the code:
> 
> ---
> title: "Test_checkdown"
> author: "Поздняков Иван"
> date: "13 02 2020"
> output: html_document
> ---
> 
> {r setup, include=FALSE}
> knitr::opts_chunk$set(echo = TRUE)
> library(checkdown)
>
> 
> {r, results='asis'}
> autocheck_question(question_id = 1, answer =  4)
> 
>

**Comment by agricolamz** [comment]
Hi, it is because in the current version you obligatory need run `autocheck_code()` function. I will try to rid of it in the future.
