### ISSUE TITLE
Obtain a score associated with a question?

### ISSUE THREAD

**Issue by Julieblas** [agricolamz/checkdown#7]
Hi !
Thanks for this package
Really well documented and easy to used

Is it possible to generate points associated with a question in order to generate a final score ?

Many thanks

**Comment by agricolamz** [comment]
Hi, @Julieblas, I'm glad that you found my package useful.

Right now it is not possible to generate a final score, but this should be possible to make. I will think about it in the following month, and hopefully will come up with some solution. Thank you for the idea!

**Comment by agricolamz** [comment]
@Julieblas, hey, I've made it (see the end of the first part in docs)! How do you want to be mentioned?

**Comment by Julieblas** [comment]
Hi,

Thanks for mentioning me, I'm ok with my Github name

I have installed version 0.0.10 of the package but get an error with the `insert_score()` function
The function is not found

Can you look at it please ?

Thanks
Julie

**Comment by agricolamz** [comment]
Cool!

Right now I've done it in the development version, v 0.1.11, that can be downloaded via `remotes::install_github("agricolamz/checkdown")`. I was waiting for you to answer the question about mentioning you. Now, when everything settled, I'll submit the new version to CRAN.

**Comment by agricolamz** [comment]
On CRAN
